//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aaaaaa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public int movieID { get; set; }
        public string Title { get; set; }
        public string Released { get; set; }
        public string Director { get; set; }
        public string Genre { get; set; }
        public string Actors { get; set; }
        public string Poster { get; set; }
        public string movieUrl { get; set; }
        public string imdbVotes { get; set; }
        public string Runtime { get; set; }
        public string Country { get; set; }
        public string BoxOffice { get; set; }
        public string imdbRating { get; set; }
    }
}
